<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\Container7Ly9w5W\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7Ly9w5W/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7Ly9w5W.legacy');
=======
if (\class_exists(\ContainerFfSXPuZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFfSXPuZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFfSXPuZ.legacy');
>>>>>>> 5085d8bd26d05fd957697ee818f531f0823619bc

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\Container7Ly9w5W\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7Ly9w5W\App_KernelDevDebugContainer([
    'container.build_hash' => '7Ly9w5W',
    'container.build_id' => 'e4278869',
    'container.build_time' => 1617318371,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7Ly9w5W');
=======
    \class_alias(\ContainerFfSXPuZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFfSXPuZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'FfSXPuZ',
    'container.build_id' => '4afc457a',
    'container.build_time' => 1617291083,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFfSXPuZ');
>>>>>>> 5085d8bd26d05fd957697ee818f531f0823619bc
