<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7Ly9w5W\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7Ly9w5W/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7Ly9w5W.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7Ly9w5W\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7Ly9w5W\App_KernelDevDebugContainer([
    'container.build_hash' => '7Ly9w5W',
    'container.build_id' => 'e4278869',
    'container.build_time' => 1617318371,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7Ly9w5W');
